[project]
name = "boucle"
version = "0.1.0"
description = "Platform-agnostic I/O library for Mojo"
license = "MIT"
requires-python = ">=3.11"
dependencies = [
    "mojox>=0.2",
    "mojo-compiler==1.0.0b1",
]

[build-system]
requires = [
    "mojox-build>=0.2",
    "mojo-compiler==1.0.0b1",
    "mojo-compiler-mojo-libs==1.0.0b1",
]
build-backend = "mojox_build"

[tool.uv]
prerelease = "allow"

[tool.mojox-build]
packages = ["boucle"]
